package com.minidb.sql;


import com.minidb.sql.ast.*;
import com.minidb.sql.generated.SQLBaseVisitor;
import com.minidb.sql.generated.SQLParser;

import java.util.*;

/**
 * ASTBuilder traverses the parse tree generated by ANTLR and constructs an Abstract Syntax Tree (AST)
 * representing the SQL statements. It extends SQLBaseVisitor, allowing it to override visit methods
 * for different SQL constructs.
 * The ASTBuilder handles SELECT, INSERT, CREATE DATABASE, and CREATE TABLE statements, as well as
 * expressions like literals, column references, and comparisons.
 * This class is crucial for transforming the raw parse tree into a more structured and easily manipulable form (the AST),
 * which can then be used for query execution or further analysis.
 * Note: The AST classes (e.g., SelectStatement, InsertStatement, Expression, etc.) are assumed to be defined in the com.minidb.sql.ast package.
 * Author: Ashutosh Dang
 */
public class ASTBuilder extends SQLBaseVisitor<Object> {

    @Override
    public Object visitParse(SQLParser.ParseContext ctx) {
        return visit(ctx.statement());
    }

    @Override
    public Statement visitSelectStatement(SQLParser.SelectStatementContext ctx) {
        if (ctx.groupByClause() != null || ctx.havingClause() != null || ctx.orderByClause() != null || ctx.limitClause() != null) {
            throw new UnsupportedOperationException("GROUP BY, HAVING, ORDER BY, and LIMIT are not implemented yet");
        }

        List<SelectItem> items = new ArrayList<>();

        if (ctx.selectElements().getText().equals("*")) {
            items.add(new SelectItem(new ColumnExpression("*"), null));
        } else {
            for (var el : ctx.selectElements().selectElement()) {
                Expression expr = (Expression) visit(el.expression());
                String alias = el.identifier() != null ? el.identifier().getText() : null;
                items.add(new SelectItem(expr, alias));
            }
        }

        String table = ctx.tableSource().qualifiedName().getText();

        Expression where = null;
        if (ctx.whereClause() != null) {
            where = (Expression) visit(ctx.whereClause().expression());
        }

        return new SelectStatement(items, table, where);
    }

    @Override
    public Statement visitInsertStatement(SQLParser.InsertStatementContext ctx) {

        String table = ctx.qualifiedName().getText();
        List<String> columnNames = new ArrayList<>();
        for (var identifier : ctx.identifier()) {
            columnNames.add(normalizeIdentifier(identifier.getText()));
        }

        List<Expression> values = new ArrayList<>();

        for (var v : ctx.value()) {
            values.add((Expression) visit(v));
        }

        return new InsertStatement(table, columnNames, values);
    }

    @Override
    public Statement visitUpdateStatement(SQLParser.UpdateStatementContext ctx) {
        Map<String, Expression> assignments = new LinkedHashMap<>();
        for (var assignment : ctx.assignment()) {
            assignments.put(normalizeIdentifier(assignment.identifier().getText()), (Expression) visit(assignment.expression()));
        }

        Expression where = ctx.whereClause() == null ? null : (Expression) visit(ctx.whereClause().expression());
        return new UpdateStatement(ctx.qualifiedName().getText(), assignments, where);
    }

    @Override
    public Statement visitDeleteStatement(SQLParser.DeleteStatementContext ctx) {
        Expression where = ctx.whereClause() == null ? null : (Expression) visit(ctx.whereClause().expression());
        return new DeleteStatement(ctx.qualifiedName().getText(), where);
    }

    @Override
    public Statement visitDropDatabase(SQLParser.DropDatabaseContext ctx) {
        return new DropDatabaseStatement(normalizeIdentifier(ctx.identifier().getText()), ctx.ifExists() != null);
    }

    @Override
    public Statement visitDropSchema(SQLParser.DropSchemaContext ctx) {
        return new DropSchemaStatement(ctx.qualifiedName().getText(), ctx.ifExists() != null);
    }

    @Override
    public Statement visitDropTable(SQLParser.DropTableContext ctx) {
        return new DropTableStatement(ctx.qualifiedName().getText(), ctx.ifExists() != null);
    }

    @Override
    public Statement visitBeginTransaction(SQLParser.BeginTransactionContext ctx) {
        return new BeginTransactionStatement();
    }

    @Override
    public Statement visitCommitTransaction(SQLParser.CommitTransactionContext ctx) {
        return new CommitTransactionStatement();
    }

    @Override
    public Statement visitRollbackTransaction(SQLParser.RollbackTransactionContext ctx) {
        return new RollbackTransactionStatement();
    }

    @Override
    public Expression visitValue(SQLParser.ValueContext ctx) {
        if (ctx.NULL() != null) {
            return new LiteralExpression(null);
        }
        return (Expression) visit(ctx.literal());
    }

    @Override
    public Expression visitLiteral(SQLParser.LiteralContext ctx) {
        if (ctx.NUMBER() != null) {
            return new LiteralExpression(Integer.parseInt(ctx.NUMBER().getText()));
        }
        if (ctx.FLOAT_NUMBER() != null) {
            return new LiteralExpression(Double.parseDouble(ctx.FLOAT_NUMBER().getText()));
        }
        if (ctx.TRUE() != null) {
            return new LiteralExpression(Boolean.TRUE);
        }
        if (ctx.FALSE() != null) {
            return new LiteralExpression(Boolean.FALSE);
        }
        return new LiteralExpression(unquoteString(ctx.STRING_LITERAL().getText()));
    }

    @Override
    public Expression visitColumnReference(SQLParser.ColumnReferenceContext ctx) {
        return new ColumnExpression(ctx.getText());
    }

    @Override
    public Expression visitComparisonExpression(SQLParser.ComparisonExpressionContext ctx) {
        if (ctx.comparisonOperator() == null) {
            return (Expression) visit(ctx.additiveExpression(0));
        }

        Expression left = (Expression) visit(ctx.additiveExpression(0));
        Expression right = (Expression) visit(ctx.additiveExpression(1));

        return new BinaryExpression(left, right, ctx.comparisonOperator().getText());
    }

    @Override
    public Expression visitPredicate(SQLParser.PredicateContext ctx) {
        if (ctx.IS() != null) {
            throw new UnsupportedOperationException("IS NULL predicates are not implemented yet");
        }
        return (Expression) visit(ctx.comparisonExpression());
    }

    @Override
    public Expression visitLogicalExpression(SQLParser.LogicalExpressionContext ctx) {
        if (ctx.AND() != null) {
            Expression left = (Expression) visit(ctx.logicalExpression(0));
            Expression right = (Expression) visit(ctx.logicalExpression(1));
            return new BinaryExpression(left, right, "AND");
        }

        if (ctx.OR() != null) {
            Expression left = (Expression) visit(ctx.logicalExpression(0));
            Expression right = (Expression) visit(ctx.logicalExpression(1));
            return new BinaryExpression(left, right, "OR");
        }

        if (ctx.NOT() != null) {
            return new UnaryExpression("NOT", (Expression) visit(ctx.logicalExpression(0)));
        }

        return (Expression) visit(ctx.predicate());
    }

    @Override
    public Expression visitAdditiveExpression(SQLParser.AdditiveExpressionContext ctx) {
        Expression current = (Expression) visit(ctx.multiplicativeExpression(0));
        for (int i = 1; i < ctx.multiplicativeExpression().size(); i++) {
            String op = ctx.getChild(2 * i - 1).getText();
            Expression right = (Expression) visit(ctx.multiplicativeExpression(i));
            current = new BinaryExpression(current, right, op);
        }
        return current;
    }

    @Override
    public Expression visitMultiplicativeExpression(SQLParser.MultiplicativeExpressionContext ctx) {
        Expression current = (Expression) visit(ctx.primaryExpression(0));
        for (int i = 1; i < ctx.primaryExpression().size(); i++) {
            String op = ctx.getChild(2 * i - 1).getText();
            Expression right = (Expression) visit(ctx.primaryExpression(i));
            current = new BinaryExpression(current, right, op);
        }
        return current;
    }

    @Override
    public Statement visitCreateDatabase(SQLParser.CreateDatabaseContext ctx) {
        return new CreateDatabaseStatement(normalizeIdentifier(ctx.identifier().getText()));
    }

    @Override
    public Statement visitCreateSchema(SQLParser.CreateSchemaContext ctx) {
        return new CreateSchemaStatement(ctx.qualifiedName().getText());
    }

    @Override
    public Statement visitCreateTable(SQLParser.CreateTableContext ctx) {
        String tableName = ctx.qualifiedName().getText();
        List<ColumnDefinition> cols = new ArrayList<>();
        for (var c : ctx.columnDef()) {
            cols.add((ColumnDefinition) visit(c));
        }
        return new CreateTableStatement(tableName, cols);
    }

    @Override
    public ColumnDefinition visitColumnDef(SQLParser.ColumnDefContext ctx) {
        if (!ctx.columnConstraint().isEmpty()) {
            throw new UnsupportedOperationException("Column constraints are not implemented yet");
        }
        return new ColumnDefinition(
            normalizeIdentifier(ctx.identifier().getText()),
            ctx.typeName().getText()
        );
    }

    @Override
    public Expression visitFunctionCall(SQLParser.FunctionCallContext ctx) {
        String functionName = ctx.functionName().getText().toUpperCase(Locale.ROOT);
        FunctionCallExpression.AggregateFunction function = FunctionCallExpression.AggregateFunction.valueOf(functionName);
        Expression argument = ctx.STAR() != null ? null : (Expression) visit(ctx.expression());
        return new FunctionCallExpression(function, argument);
    }

    private String normalizeIdentifier(String text) {
        if (text.startsWith("`") && text.endsWith("`") && text.length() >= 2) {
            return text.substring(1, text.length() - 1);
        }
        return text;
    }

    private String unquoteString(String text) {
        String unquoted = text.substring(1, text.length() - 1);
        return unquoted.replace("\\'", "'").replace("\\\\", "\\");
    }
}