package com.minidb.jdbc;

import java.sql.*;
import java.util.List;

/**
 * MiniDB JDBC Statement implementation.
 *
 * Supports:
 *  - executeQuery()  → SELECT statements
 *  - executeUpdate() → INSERT / UPDATE / DELETE / DDL
 *  - execute()       → any SQL
 */
public class MiniDbStatement implements Statement {

    protected final MiniDbConnection connection;
    private ResultSet currentResultSet;
    private int       updateCount  = -1;
    private boolean   closed       = false;
    private int       maxRows      = 0;
    private int       queryTimeout = 0;

    MiniDbStatement(MiniDbConnection connection) {
        this.connection = connection;
    }

    // ── Core execution ─────────────────────────────────────────────────────

    @Override
    public ResultSet executeQuery(String sql) throws SQLException {
        checkOpen();
        List<String> lines = connection.execute(sql);
        currentResultSet = MiniDbResultSet.fromLines(lines);
        updateCount = -1;
        return currentResultSet;
    }

    @Override
    public int executeUpdate(String sql) throws SQLException {
        checkOpen();
        List<String> lines = connection.execute(sql);
        currentResultSet = null;
        updateCount = parseUpdateCount(lines);
        return updateCount;
    }

    @Override
    public boolean execute(String sql) throws SQLException {
        checkOpen();
        List<String> lines = connection.execute(sql);
        String first = lines.isEmpty() ? "" : lines.get(0);
        if (first.matches("\\d+ ROW.*") || "OK".equals(first)
                || first.contains("CREATED") || first.contains("DROPPED")
                || first.contains("STARTED") || first.contains("COMMITTED")
                || first.contains("ROLLED BACK")) {
            currentResultSet = null;
            updateCount = parseUpdateCount(lines);
            return false;  // update / DDL
        }
        currentResultSet = MiniDbResultSet.fromLines(lines);
        updateCount = -1;
        return true;  // query
    }

    @Override
    public ResultSet getResultSet() { return currentResultSet; }

    @Override
    public int getUpdateCount() { return updateCount; }

    @Override
    public boolean getMoreResults() { return false; }

    // ── State ──────────────────────────────────────────────────────────────

    @Override
    public void close() { closed = true; currentResultSet = null; }

    @Override
    public boolean isClosed() { return closed; }

    @Override
    public Connection getConnection() { return connection; }

    @Override
    public void setMaxRows(int max) { maxRows = max; }

    @Override
    public int getMaxRows() { return maxRows; }

    @Override
    public void setQueryTimeout(int seconds) { queryTimeout = seconds; }

    @Override
    public int getQueryTimeout() { return queryTimeout; }

    @Override
    public void cancel() {}

    @Override
    public SQLWarning getWarnings() { return null; }

    @Override
    public void clearWarnings() {}

    // ── Helpers ────────────────────────────────────────────────────────────

    private void checkOpen() throws SQLException {
        if (closed) throw new SQLException("Statement is closed");
    }

    private int parseUpdateCount(List<String> lines) {
        if (lines.isEmpty()) return 0;
        String first = lines.get(0);
        try {
            return Integer.parseInt(first.split(" ")[0]);
        } catch (NumberFormatException e) {
            return 0;
        }
    }

    // ── Unsupported / stubs ────────────────────────────────────────────────

    @Override public void setCursorName(String name) {}
    @Override public int[] executeBatch() throws SQLException { throw new SQLFeatureNotSupportedException(); }
    @Override public void addBatch(String sql) {}
    @Override public void clearBatch() {}
    @Override public void setEscapeProcessing(boolean enable) {}
    @Override public void setFetchDirection(int direction) {}
    @Override public int getFetchDirection() { return ResultSet.FETCH_FORWARD; }
    @Override public void setFetchSize(int rows) {}
    @Override public int getFetchSize() { return 0; }
    @Override public int getResultSetConcurrency() { return ResultSet.CONCUR_READ_ONLY; }
    @Override public int getResultSetType() { return ResultSet.TYPE_FORWARD_ONLY; }
    @Override public int getResultSetHoldability() { return ResultSet.CLOSE_CURSORS_AT_COMMIT; }
    @Override public boolean isPoolable() { return false; }
    @Override public void setPoolable(boolean poolable) {}
    @Override public void closeOnCompletion() {}
    @Override public boolean isCloseOnCompletion() { return false; }
    @Override public boolean execute(String sql, int autoGeneratedKeys) throws SQLException { return execute(sql); }
    @Override public boolean execute(String sql, int[] columnIndexes) throws SQLException { return execute(sql); }
    @Override public boolean execute(String sql, String[] columnNames) throws SQLException { return execute(sql); }
    @Override public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException { return executeUpdate(sql); }
    @Override public int executeUpdate(String sql, int[] columnIndexes) throws SQLException { return executeUpdate(sql); }
    @Override public int executeUpdate(String sql, String[] columnNames) throws SQLException { return executeUpdate(sql); }
    @Override public ResultSet getGeneratedKeys() throws SQLException { return MiniDbResultSet.empty(); }
    @Override public boolean getMoreResults(int current) { return false; }
    @Override public int getMaxFieldSize() { return 0; }
    @Override public void setMaxFieldSize(int max) {}
    @Override public long getLargeUpdateCount() { return updateCount; }
    @Override public long getLargeMaxRows() { return maxRows; }
    @Override public void setLargeMaxRows(long max) {}
    @Override public <T> T unwrap(Class<T> iface) throws SQLException { throw new SQLFeatureNotSupportedException(); }
    @Override public boolean isWrapperFor(Class<?> iface) { return false; }
}
